/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Controlador;
import Controlador.Eventos;
import javax.swing.JOptionPane;

/**
 *
 * @author crash
 */
public class Login extends javax.swing.JFrame implements IGUI {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelContrasena = new javax.swing.JLabel();
        fieldContrasena = new javax.swing.JPasswordField();
        botonAceptarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(400, 150));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelContrasena.setText("Contrasena");
        getContentPane().add(labelContrasena, new java.awt.GridBagConstraints());

        fieldContrasena.setMaximumSize(new java.awt.Dimension(180, 22));
        fieldContrasena.setMinimumSize(new java.awt.Dimension(180, 22));
        fieldContrasena.setPreferredSize(new java.awt.Dimension(180, 22));
        fieldContrasena.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 18);
        getContentPane().add(fieldContrasena, gridBagConstraints);

        botonAceptarContrasena.setText("Aceptar");
        botonAceptarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptarContrasena, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarContrasenaActionPerformed
        Usuario user =  new Usuario("admin", String.valueOf(this.fieldContrasena.getPassword()));
        Controlador.getInstancia().accion(Eventos.COMPROBAR_LOGIN, user);
    }//GEN-LAST:event_botonAceptarContrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarContrasena;
    private javax.swing.JPasswordField fieldContrasena;
    private javax.swing.JLabel labelContrasena;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(Eventos evento, Object datos) {
        if (evento == Eventos.LOGIN_OK){
            Controlador.getInstancia().accion(Eventos.MOSTRAR_MENU, null);
        } else if (evento == Eventos.LOGIN_ERROR){
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
        } else if (evento == Eventos.MOSTRAR_LOGIN){
            this.setVisible(true);
        }
    }
}
