/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Controlador;
import Controlador.Eventos;
import javax.swing.JFormattedTextField;

/**
 *
 * @author carlos
 */
public class PanelEquipos extends javax.swing.JPanel {

    /**
     * Creates new form panelEquipos
     */
    public PanelEquipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipoIzquierdaArriba = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        equipoDerechaArriba = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        equipoIzquiedaFinal = new javax.swing.JFormattedTextField();
        equipoDerechaFinal = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        equipoIzquierdaAbajo = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        equipoDerechaAbajo = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 2, 2, 10));
        setLayout(new java.awt.GridLayout(3, 4, 5, 5));

        equipoIzquierdaArriba.setBackground(new java.awt.Color(102, 102, 102));
        equipoIzquierdaArriba.setForeground(new java.awt.Color(0, 0, 0));
        equipoIzquierdaArriba.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoIzquierdaArriba.setText("equipo1");
        equipoIzquierdaArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equipoPulsadoIzquierda(evt);
            }
        });
        equipoIzquierdaArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoIzquierdaArribaActionPerformed(evt);
            }
        });
        add(equipoIzquierdaArriba);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel2);

        equipoDerechaArriba.setBackground(new java.awt.Color(102, 102, 102));
        equipoDerechaArriba.setForeground(new java.awt.Color(0, 0, 0));
        equipoDerechaArriba.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoDerechaArriba.setText("equipo3");
        equipoDerechaArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equipoPulsadoDerecha(evt);
            }
        });
        add(equipoDerechaArriba);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel3);

        equipoIzquiedaFinal.setEditable(false);
        equipoIzquiedaFinal.setBackground(new java.awt.Color(102, 102, 102));
        equipoIzquiedaFinal.setForeground(new java.awt.Color(0, 0, 0));
        equipoIzquiedaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoIzquiedaFinal.setText("finalista1");
        equipoIzquiedaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoIzquiedaFinalActionPerformed(evt);
            }
        });
        add(equipoIzquiedaFinal);

        equipoDerechaFinal.setEditable(false);
        equipoDerechaFinal.setBackground(new java.awt.Color(102, 102, 102));
        equipoDerechaFinal.setForeground(new java.awt.Color(0, 0, 0));
        equipoDerechaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoDerechaFinal.setText("finalista2");
        equipoDerechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoDerechaFinalActionPerformed(evt);
            }
        });
        add(equipoDerechaFinal);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel4);

        equipoIzquierdaAbajo.setBackground(new java.awt.Color(102, 102, 102));
        equipoIzquierdaAbajo.setForeground(new java.awt.Color(0, 0, 0));
        equipoIzquierdaAbajo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoIzquierdaAbajo.setText("equipo2");
        equipoIzquierdaAbajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equipoPulsadoIzquierda(evt);
            }
        });
        add(equipoIzquierdaAbajo);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        add(jPanel6);

        equipoDerechaAbajo.setBackground(new java.awt.Color(102, 102, 102));
        equipoDerechaAbajo.setForeground(new java.awt.Color(0, 0, 0));
        equipoDerechaAbajo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipoDerechaAbajo.setText("equipo4");
        equipoDerechaAbajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equipoPulsadoDerecha(evt);
            }
        });
        add(equipoDerechaAbajo);
    }// </editor-fold>//GEN-END:initComponents

    private void equipoIzquiedaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoIzquiedaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipoIzquiedaFinalActionPerformed

    private void equipoDerechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoDerechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipoDerechaFinalActionPerformed

    private void equipoPulsadoIzquierda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipoPulsadoIzquierda
       Controlador.getInstancia().accion(Eventos.setFinalistaIz,((JFormattedTextField)evt.getComponent()).getText());
    }//GEN-LAST:event_equipoPulsadoIzquierda

    private void equipoIzquierdaArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoIzquierdaArribaActionPerformed
        
    }//GEN-LAST:event_equipoIzquierdaArribaActionPerformed

    private void equipoPulsadoDerecha(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipoPulsadoDerecha
         Controlador.getInstancia().accion(Eventos.setFinalistaDe,((JFormattedTextField)evt.getComponent()).getText());
    }//GEN-LAST:event_equipoPulsadoDerecha


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField equipoDerechaAbajo;
    private javax.swing.JFormattedTextField equipoDerechaArriba;
    private javax.swing.JFormattedTextField equipoDerechaFinal;
    private javax.swing.JFormattedTextField equipoIzquiedaFinal;
    private javax.swing.JFormattedTextField equipoIzquierdaAbajo;
    private javax.swing.JFormattedTextField equipoIzquierdaArriba;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    void setTextEquipoIzquierdaArriba(String s)
    {
        this.equipoIzquierdaArriba.setText(s);
    }
    
     void setTextEquipoIzquierdaAbajo(String s)
    {
        this.equipoIzquierdaAbajo.setText(s);
    }
     
     void setTextEquipoIzquierdaFinal(String s)
    {
        this.equipoIzquiedaFinal.setText(s);
    }
     
     
     
     
     
      void setTextEquipoDerechaArriba(String s)
    {
        this.equipoDerechaArriba.setText(s);
    }
      
      void setTextEquipoDerechaAbajo(String s)
    {
        this.equipoDerechaAbajo.setText(s);
    }
      
       void setTextEquipoDerechaFinal(String s)
    {
        this.equipoDerechaFinal.setText(s);
    }
     
}

